# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/finfox',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/finfox',
                'lib_path': 'finfox'},
  'syms': { 'finfox.core': { 'finfox.core.devide_img': ('core.html#devide_img', 'finfox/core.py'),
                             'finfox.core.download_rename': ('core.html#download_rename', 'finfox/core.py'),
                             'finfox.core.download_url': ('core.html#download_url', 'finfox/core.py'),
                             'finfox.core.make_dirs': ('core.html#make_dirs', 'finfox/core.py'),
                             'finfox.core.pdf2imgOffset': ('core.html#pdf2imgoffset', 'finfox/core.py'),
                             'finfox.core.pdfPC': ('core.html#pdfpc', 'finfox/core.py'),
                             'finfox.core.rn_zip_extract': ('core.html#rn_zip_extract', 'finfox/core.py'),
                             'finfox.core.save_md': ('core.html#save_md', 'finfox/core.py')},
            'finfox.serverMLX': {'finfox.serverMLX.test_server': ('servermlx.html#test_server', 'finfox/serverMLX.py')}}}
