"""use google genai to process data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_extractGemini.ipynb.

# %% auto 0
__all__ = ['gemini_key', 'promt_helper', 'im_open', 'md']

# %% ../nbs/02_extractGemini.ipynb 2
from fastcore.utils import *
from fastcore.xtras import *
from .core import *
import pandas as pd

# %% ../nbs/02_extractGemini.ipynb 4
import os
from dotenv import load_dotenv
from google import genai
load_dotenv()
gemini_key = os.environ["GEMINI_KEY1"]

# %% ../nbs/02_extractGemini.ipynb 5
def promt_helper(s): 
    response = client.models.generate_content(
        model="gemini-1.5-flash", 
        contents=f"Write an efficient prompt for llm for the task: {s}",
    )
    return response.text

# %% ../nbs/02_extractGemini.ipynb 13
from PIL import Image
def im_open(fn:Path):
    """
    open an image and return image
    """
    return Image.open(fn)

# %% ../nbs/02_extractGemini.ipynb 16
import re
def md(text: str) -> list:
    """
    Extract text wrapped in markdown-style triple backticks.
    - list: A list of extracted strings.
    """
    pattern = r'```(?:markdown)?(.*?)```'  # Match ```markdown <text> ```
    return [match.strip() for match in re.findall(pattern, text, re.DOTALL)]
